Iter13
kerelape/urlshortener pull request #14
Opened 2023-04-05 19:56 UTC by kerelape

2023-04-12 15:35 UTC, tmvrus requested changes
А почему принято решение не сохранять пользователя в базу?

2023-04-12 15:35 UTC, tmvrus commented on internal/app/model/storage/postgresql_database.go
> +}
не самый удачный дизайн для добавления новых значений:

1. Между двумя запросами может случиться вставка и тогда в базе будет дубль, нужно добавлять unique constraint для поля url

2. В документации QueryRow написано
```
// If the query selects no rows, the *Row's Scan will return ErrNoRows.
```
таким образом, ошибка ErrNoRows порождает ошибку NewDuplicateValueError, а это логическое противоречие 

3. вместо QueryRow следует использовать QueryRowContext, QueryRow появился еще до того как в Go пришли контексты и нужен только для обратной совместимости, это касается всех методов работы с базой. Контекст нужно брать из http.Request

2023-04-12 15:35 UTC, tmvrus commented on internal/app/model/storage/postgresql_database.go
> +	transaction, beginError := database.db.Begin()
что бы получить список значений не нужна транзакция, достаточно одно запроса с условием ANY/IN
https://www.postgresql.org/docs/current/functions-comparisons.html

2023-04-12 15:35 UTC, tmvrus commented on internal/app/ui/api/shorten/batch_api.go
> +	response := make([]*batchAPIResponseNode, len(request))
почему используется `[]*batchAPIResponseNode` а не `[]batchAPIResponseNode` ?

2023-04-12 15:35 UTC, tmvrus commented on internal/app/ui/api/user/urls_api.go
> +	} else {
else лишний, выше есть return

2023-04-12 15:35 UTC, tmvrus commented on internal/app/ui/sql_ping.go
> +			}
можно записать короче:
```go
status := http.StatusOK
pingError := ping.database.Ping()
if pingError != nil {
    status := http.StatusInternalServerError
}
http.Error(rw, http.StatusText(status), status)
```

2023-04-13 01:49 UTC, kerelape commented
> А почему принято решение не сохранять пользователя в базу?

Не было такого требования

2023-04-13 02:49 UTC, kerelape commented on internal/app/ui/api/shorten/batch_api.go
> +	response := make([]*batchAPIResponseNode, len(request))
уже не помню - скорее всего, какое-то ошибочное представление о том, как работают слайсы (возможно пытался избежать копирования массива)

2023-04-13 03:39 UTC, kerelape commented on internal/app/model/storage/postgresql_database.go
> +}
Недоконца понимаю пункт 2 - как получить id оригина?

2023-04-14 07:02 UTC, tmvrus approved these changes
Хорошая работа.

2023-04-14 07:42 UTC, merged